config/routes.rb
Rails.application.routes.draw do
  resources  :sessions, only: [:new, :create, :destroy]
  resources  :posts, only: [:new, :create, :index]

  match '/signin', to: 'sessions#new',   via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { minimum: 1 }
  validate :body, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  has_many :posts
  validates :name, presence: true
  validates :email, presence: true


  has_secure_password
  validates :password, length: { minimum: 6 }



  def User.new_remember_token
      SecureRandom.urlsafe_base64
  end

  def User.digest(token)
      Digest::SHA1.hexdigest(token.to_s)
  end


    private

      def create_remember_token
        self.remember_token = User.digest(User.new_remember_token)
      end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create]

def index
  @posts = Post.all

end

def new
  @post = Post.new

end

def create
  @post = Post.new(post_params)
  @post.user_id = current_user.id

  if @post.save
    redirect_to root_path
  else
    render 'new'
  end
end


private

    def signed_in_user
      unless signed_in?
        redirect_to sign_in_url
      end
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
    else

      flash.now[:error] = 'Invalid/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end



  def sign_out
    current_user.update_attribute(:remember_token,
                                User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
      <% if signed_in? %>
          <%= link_to "Sign out", signout_path, method: "delete" %>
      <% end %>


    </header>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% unless signed_in? %>
<%= link_to "Sign in", signin_path %>
<% end %>

<h1>Members Only Posts</h1>

<% @posts.each do |post| %>
<% if signed_in? %>

<p>
Posted by:

</p><%= post.user.name %>
<% end %>

<h4><%=post.title %></h4>
<p><%= post.body %></p>
<% end %>

<% if signed_in? %>
<%= link_to "Create a Post", new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>Create a Post</h1>
<% if @post.errors.any? %>
<p>Your submission has <%= pluralize(@post.errors.count, 'error') %>
<ul>
  <% @post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @post do |p| %>

<p>
    <%= p.label :title %>
    <%= p.text_field :title %>
</p>
<p>
    <%= p.label :body %></br>
    <%= p.text_area :body %>
</p>

<p>
  <%= p.submit "Create" %>
</p>
<% end %>